/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: { center: true, padding: "2rem" },
    extend: {
      colors: {
        border:       "hsl(var(--border))",
        input:        "hsl(var(--input))",
        ring:         "hsl(var(--ring))",
        background:   "hsl(var(--background))",
        foreground:   "hsl(var(--foreground))",
        primary: {
          DEFAULT:    "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT:    "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT:    "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT:    "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT:    "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT:    "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT:    "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        // Editorial Architect custom tokens
        "tertiary": "#003d27",
        "surface-dim": "#d8dadc",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001453",
        "on-surface": "#191c1e",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-primary": "#b8c4ff",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed": "#dde1ff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#3fd298",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c4c5d5",
        "on-secondary-fixed-variant": "#3b446e",
        "primary-container": "#1e40af",
        "surface-bright": "#f7f9fb",
        "on-surface-variant": "#444653",
        "secondary-container": "#c3ccfe",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#173bab",
        "primary-fixed": "#dde1ff",
        "surface-tint": "#3755c3",
        "outline": "#757684",
        "on-background": "#191c1e",
        "on-secondary-container": "#4c5680",
        "tertiary-container": "#00563a",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#bbc4f6",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary-fixed": "#002113",
        "surface-container-high": "#e6e8ea",
        "on-secondary-fixed": "#0e1840",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "on-primary-container": "#a8b8ff",
        "tertiary-fixed": "#6ffbbe"
      },
      borderRadius: {
        lg:   "var(--radius)",
        md:   "calc(var(--radius) - 2px)",
        sm:   "calc(var(--radius) - 4px)",
        xl:   "calc(var(--radius) + 4px)",
        "2xl":"calc(var(--radius) + 8px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        headline: ["Inter"],
        body: ["Inter"],
        label: ["Inter"],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', "Liberation Mono", "Courier New", 'monospace'],
      },
      keyframes: {
        "fade-in":  { from: { opacity: "0", transform: "translateY(6px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.96)" }, to: { opacity: "1", transform: "scale(1)" } },
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":   { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "fade-in":        "fade-in 0.2s ease-out",
        "slide-up":       "slide-up 0.25s ease-out",
        "scale-in":       "scale-in 0.15s ease-out",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
      },
      boxShadow: {
        "surface-sm": "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        "surface-md": "0 4px 12px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.04)",
        "surface-lg": "0 10px 30px rgba(0,0,0,0.08), 0 4px 8px rgba(0,0,0,0.04)",
        "primary-glow": "0 4px 14px rgba(47,80,163,0.25)",
      },
    },
  },
  plugins: [],
}
